### ISSUE TITLE
您好，将这些dll放入tvm文件夹下吗

### ISSUE THREAD

**Issue by heyanglearning** [GalAster/tvm-clib-win#1]
我将dll都分别都拷贝到:
tvm/python
tvm/topi/python
tvm/nnvm/python
然后pip 进入文件夹install，tvm安装成功；topi和nnvm都出现问题，加载不到一堆dll

**Comment by heyanglearning** [comment]
后来安装成功了，但是import tvm显示：
`>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Hybrid\tvm\python\tvm\__init__.py", line 27, in <module>
    from . import tensor
  File "D:\Hybrid\tvm\python\tvm\tensor.py", line 20, in <module>
    from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node
  File "D:\Hybrid\tvm\python\tvm\_ffi\node.py", line 24, in <module>
    from .object import Object, register_object, _set_class_node
  File "D:\Hybrid\tvm\python\tvm\_ffi\object.py", line 23, in <module>
    from .base import _FFI_MODE, _RUNTIME_ONLY, check_call, _LIB, c_str
  File "D:\Hybrid\tvm\python\tvm\_ffi\base.py", line 60, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "D:\Hybrid\tvm\python\tvm\_ffi\base.py", line 52, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "C:\Users\Admin\.conda\envs\tvm\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。`
